result = [
       0x96,
       0x09,
       0xda,
       0xce,
       0x99,
       0xfe,
       0x51,
       0x59,
       0x25,
       0x06,
       0x1b,
       0x7c,
       0xe4,
       0xd2,
       0xdc,
       0x43,
       0x6b,
       0x96,
       0xc4,
       0xea,
       0x05,
       0x37,
       0x8c,
       0x75,
       0x84,
       0x8d,
       0xb2,
       0x1a,
       0xc6,
       0xdc,
       0x7d,
       0x32,
]
x = [0xbd, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
